print("um texto\0outro texto")
print("um texto\aoutro texto")
print("um texto\b\b\b\boutro texto")
print("um texto\toutro texto")
print("um texto\noutro texto")
print("um texto\voutro texto")
print("um texto\foutro texto")
print("um texto\routro texto")
